### ISSUE TITLE
Convenient design features

### ISSUE THREAD

**Issue by sergeyklay** [ZDroid/dotfiles#3]
Hi!
Thanks for your project - it inspired me to create my :)

I would suggest you make the following function in a separate file, in order that they can be used in any script:

```sh
info () {
  printf "\n  [ \033[34m.\033[0m ] $1"
}

success () {
  printf "\n  [ \033[32mOK\033[0m ] $1"
}

fail () {
  printf "\n  [ \033[31mFAIL\033[0m ] $1"
  exit 1
}

question () {
  printf "\n  [ \033[33m?\033[0m ] $1 "
}
```
I think that I too can move a few functions in the individual libraries. The conclusion is that: We could try to create a joint project dedicated micro utilities written in bash :)

Let's do a modular bash! What do you think about this?

**Comment by ZDroid** [comment]
I'm back :fireworks:. I'll try to make your request finished as soon as possible. :smile:

**Comment by sergeyklay** [comment]
:+1:

**Comment by ZDroid** [comment]
Please test `colorize` command now, it should work fine with `printf`.

Example:
```bash
printf "$(colorize "test" white bold blue)"
```
